services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    # host-сеть нужна для обнаружения устройств в локалке (mDNS/SSDP)
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /opt/homeassistant/config:/config:Z
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: Europe/Samara
    logging:
      driver: json-file
      options: {max-size: "10m", max-file: "3"}
