services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    volumes:
      - /opt/zigbee2mqtt/data:/app/data:Z
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Samara
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
